- hosts: all
  become: true  
  tasks:
    - name: Configure a MOTD (message of the day)
      copy:
        content: "Welcome to {{ item }}!\n"
        dest: /etc/motd
      notify: MOTD changed
      with_items: [ 'RedHat', 'SLES' ]
      when: ansible_distribution == item
 
  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed
...
