---
- hosts: all
  become: True
  gather_facts: True
  tasks:
    - name: Run a command
      shell:  hostname
      register: output
    - name: Display output
      debug:
         msg: "{{ output.stdout_lines }}"
...
      
