- hosts: all
  gather_facts: false
  vars:
    named_list:
      - item1
      - item2
      - item3
      - item4
  tasks: 
    - name: Test dict1ionary value
      debug:
        msg: "{{ named_list }}"
    - name: Test key 1 of dict1ionary
      debug:
        msg: "{{ named_list.0 }}"
    - name: Test key2 with python brackets
      debug:
        msg: "{{ named_list[0]}}"
